title: "Daily Alertmanager digest"
dryRun: false
timeout: 10s

alertmanagers:
- name: c2
  url: https://alertmanager.c2.bethink.tech
- name: c3
  url: https://alertmanager.c3.bethink.tech

filters:
- severity=~"warning|critical"
# - team=ops

displayLabels:
# - "*"
- severity
- alertname
- cluster
- namespace
- team

# excludeLabels:
# - prometheus
# - prometheus_namespace

slack:
  sendEmptyMessage: true
  maxAlerts: 40

http:
  insecureSkipVerify: false


history:
  enabled: true
  # Defaults to 24h. Can be overridden with --history-window.
  window: 24h
  # Defaults to GOOGLE_CLOUD_PROJECT or GCLOUD_PROJECT when omitted.
  projectIds:
  - bethink-prod
  - bethink-ecommerce
  # Defaults to alertmanager-webhook-logger container logs with message "Events received".
  # filter: 'resource.type="k8s_container" AND resource.labels.container_name="alertmanager-webhook-logger" AND jsonPayload.message="Events received"'
  # Defaults to slack.maxAlerts.
  maxAlerts: 40
  # Defaults to 1000.
  pageSize: 1000
